### PR TITLE
Fix/incorrect polynomial evaluation

### LINKED ISSUE #540: bug: variable not assigned
## Description

l.184 polynomial.go in iop/ package: 
```
        bs := big.NewInt(int64(p.shift))
	g = *g.Exp(g, bs) // <----- variable g is not assigned at this stage
	x.Mul(&x, &g)
	return p.polynomial.evaluate(x)
```

### PR DESCRIPTION
**Pull request by ThomasPiellard**
# Description

Variable was not assigned when evaluating a shifted polynomial with shift > 5.

Fixes #540 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I did not modify files generated from templates
- [x] `golangci-lint` does not output errors locally
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: internal/generator/iop/template/polynomial.go.tmpl [hunk 1]
```diff
@@ -152,8 +152,8 @@ func (p *Polynomial) Evaluate(x fr.Element) fr.Element {
 	}
 
 	var g fr.Element
+	gen, err := fft.Generator(uint64(p.size))
 	if p.shift <= 5 {
-		gen, err := fft.Generator(uint64(p.size))
 		if err != nil {
```
Comment (gbotrel) [inline internal/generator/iop/template/polynomial.go.tmpl:157]: this err check should be moved outside the `if` scope

**Review by gbotrel — CHANGES_REQUESTED** [review]

**Review by ivokub — APPROVED** [review]
LGTM

**Review by gbotrel — APPROVED** [review]
