### PR TITLE
fix: mimc is compliant with ethereum

### LINKED ISSUE #124: Mimc implementation consistant with ethereum implementation
mimc on gnark-crypto should be consistant with [this](https://gist.github.com/HarryR/80b5ff2ce13da12edafda6d21c780730) implementation.

### PR DESCRIPTION
**Pull request by ThomasPiellard**
Fixes #124 .

Example:
```
var data [3]fr.Element
	data[0].SetString("10909369219534740878285360918369814291778422174980871969149168794639722256599")
	data[1].SetString("3811523387212735178398974960485340561880938762308498768570292593755555588442")
	data[2].SetString("21761276089180230617904476026690048826689721630933485969915548849196498965166")

	h := NewMiMC("mimc")
	h.Write(data[0].Marshal())
	h.Write(data[1].Marshal())
	h.Write(data[2].Marshal())

	r := h.Sum(nil)

	var b big.Int
	b.SetBytes(r)
	fmt.Printf("%s\n", b.String())
```
outputs `7018430971635270450834876734052312213264841464458602476370836768879919501996`

, as does [this](https://gist.github.com/HarryR/80b5ff2ce13da12edafda6d21c780730) implementation ->
 on python with `DEFAULT_EXPONENT = 5` and `DEFAULT_SEED = "mimc"`:
```
In [3]: mimc_hash([
   ...: 10909369219534740878285360918369814291778422174980871969149168794639722256599,
   ...: 3811523387212735178398974960485340561880938762308498768570292593755555588442,
   ...: 21761276089180230617904476026690048826689721630933485969915548849196498965166])
Out[3]: 7018430971635270450834876734052312213264841464458602476370836768879919501996
```

### CODE REVIEW

File: internal/generator/crypto/hash/mimc/template/mimc.go.tmpl [hunk 1]
```diff
@@ -130,31 +144,31 @@ func (d *digest) checksum() fr.Element {
...
-func (d *digest) encrypt(m fr.Element) {
+func (d *digest) encrypt(m fr.Element) (e fr.Element){
 
 	for i:=0; i < len(d.Params); i++ {
 		// m = (m+k+c)^**-1
 		m.Add(&m, &d.h).Add(&m, &d.Params[i]).Inverse(&m)
 	}
-	m.Add(&m, &d.h)
-	d.h = m
+	e.Add(&m, &d.h)
```
Comment (gbotrel) [inline internal/generator/crypto/hash/mimc/template/mimc.go.tmpl:153]: since m is passed by value, you can just do m.Add(&m, &d.h) and return m.

File: internal/generator/crypto/hash/mimc/template/mimc.go.tmpl [hunk 2]
```diff
@@ -130,31 +144,31 @@ func (d *digest) checksum() fr.Element {
...
 		// m = (m+k+c)^5
 		var tmp fr.Element
 		tmp.Add(&m, &d.h).Add(&tmp, &d.Params[i])
 		m.Square(&tmp).
 			Square(&m).
 			Mul(&m, &tmp)
 	}
-	m.Add(&m, &d.h)
-	d.h = m
+	e.Add(&m, &d.h)
```
Comment (gbotrel) [inline internal/generator/crypto/hash/mimc/template/mimc.go.tmpl:170]: same

**Review by gbotrel — APPROVED** [review]
