### PR TITLE
fix: fixes #619 help go mod vendor to include files

### LINKED ISSUE #619: bug: broken vendoring in gnark-crypto@0.15.0
## Description

When using vendoring (`go mod vendor`) and then compiling dependencies, an error appears regarding missing `.s` files.

I'll demonstrate the compilation error using the [gowaves](https://github.com/wavesplatform/gowaves) project as an example.
When attempting to build the executable, the following error messages appear from the go compiler.

<details><summary>Go compiler output</summary>
<p>

```sh
# github.com/consensys/gnark-crypto/ecc/bls12-377/fp
vendor/github.com/consensys/gnark-crypto/ecc/bls12-377/fp/element_amd64.s:10: #include: open /usr/local/opt/go/field/asm/element_6w_amd64.s: no such file or directory
# github.com/consensys/gnark-crypto/ecc/bls12-381/fp
vendor/github.com/consensys/gnark-crypto/ecc/bls12-381/fp/element_amd64.s:10: #include: open /usr/local/opt/go/field/asm/element_6w_amd64.s: no such file or directory
# github.com/consensys/gnark-crypto/ecc/bls24-315/fp
vendor/github.com/consensys/gnark-crypto/ecc/bls24-315/fp/element_amd64.s:10: #include: open /usr/local/opt/go/field/asm/element_5w_amd64.s: no such file or directory
# github.com/consensys/gnark-crypto/ecc/bls24-317/fp
vendor/github.com/consensys/gnark-crypto/ecc/bls24-317/fp/element_amd64.s:10: #include: open /usr/local/opt/go/field/asm/element_5w_amd64.s: no such file or directory
# github.com/consensys/gnark-crypto/ecc/bn254/fp
vendor/github.com/consensys/gnark-crypto/ecc/bn254/fp/element_amd64.s:10: #include: open /usr/local/opt/go/field/asm/element_4w_amd64.s: no such file or directory
# github.com/consensys/gnark-crypto/ecc/bw6-633/fp
vendor/github.com/consensys/gnark-crypto/ecc/bw6-633/fp/element_amd64.s:10: #include: open /usr/local/opt/go/field/asm/element_10w_amd64.s: no such file or directory
# github.com/consensys/gnark-crypto/ecc/bw6-761/fp
vendor/github.com/consensys/gnark-crypto/ecc/bw6-761/fp/element_amd64.s:10: #include: open /usr/local/opt/go/field/asm/element_12w_amd64.s: no such file or directory
# github.com/consensys/gnark-crypto/ecc/bn254/fr
vendor/github.com/consensys/gnark-crypto/ecc/bn254/fr/element_amd64.s:10: #include: open /usr/local/opt/go/field/asm/element_4w_amd64.s: no such file or directory
# github.com/consensys/gnark-crypto/ecc/bls12-377/fr
vendor/github.com/consensys/gnark-crypto/ecc/bls12-377/fr/element_amd64.s:10: #include: open /usr/local/opt/go/field/asm/element_4w_amd64.s: no such file or directory
# github.com/consensys/gnark-crypto/ecc/bls12-381/fr
vendor/github.com/consensys/gnark-crypto/ecc/bls12-381/fr/element_amd64.s:10: #include: open /usr/local/opt/go/field/asm/element_4w_amd64.s: no such file or directory
# github.com/consensys/gnark-crypto/ecc/bls24-315/fr
vendor/github.com/consensys/gnark-crypto/ecc/bls24-315/fr/element_amd64.s:10: #include: open /usr/local/opt/go/field/asm/element_4w_amd64.s: no such file or directory
# github.com/consensys/gnark-crypto/ecc/bls24-317/fr
vendor/github.com/consensys/gnark-crypto/ecc/bls24-317/fr/element_amd64.s:10: #include: open /usr/local/opt/go/field/asm/element_4w_amd64.s: no such file or directory
# github.com/consensys/gnark-crypto/ecc/bw6-633/fr
vendor/github.com/consensys/gnark-crypto/ecc/bw6-633/fr/element_amd64.s:10: #include: open /usr/local/opt/go/field/asm/element_5w_amd64.s: no such file or directory
# github.com/consensys/gnark-crypto/ecc/bw6-761/fr
vendor/github.com/consensys/gnark-crypto/ecc/bw6-761/fr/element_amd64.s:10: #include: open /usr/local/opt/go/field/asm/element_6w_amd64.s: no such file or directory

```

</p>

</details> 

The issue does not occur when vendoring is not used.

## Expected Behavior

Successful compilation both with and without vendoring.

## Actual Behavior

Compilation works fine without vendoring.
With `go mod vendor` compilation fails with the error described above.

## Steps to Reproduce

1. Clone [gowaves](https://github.com/wavesplatform/gowaves)
2. Run `go get github.com/consensys/gnark@v0.12.0` in the project directory (it also updates `gnark-crypto` to `0.15.0`)
3. Run `go mod tidy && go mod vendor` in the project directory
4. Run `make build-node-native` in the project directory which is equivalent to `go build -o build/bin/native/node ./cmd/node`
5. Observe the output

## Context

Vendoring support is necessary for us in the [gowaves](https://github.com/wavesplatform/gowaves) project.

## Your Environment

* gnark-crypto version used: *0.15.0*
* go version (e.g. 1.20.6): *go1.23.5* and *go1.22.11*
* Operating System and version: *macOS 14.7.2* and *ubuntu-24.04*

### PR DESCRIPTION
**Pull request by gbotrel**
# Description

Fixes #619 .

Idea is just to hint to `go mod vendor` to include some assembly file by making it believe the subfolders in `asm` are actual go packages.
(in fact they just contains dummy constants and code that won't be linked, but the .s files are "included" à-la-C-preprocessor into other .s files)

### CODE REVIEW

**Comment by ivokub** [comment]
Suggested edit:
```diff
diff --git a/field/asm/.gitignore b/field/asm/.gitignore
index d21c226a7..d9d3470d3 100644
--- a/field/asm/.gitignore
+++ b/field/asm/.gitignore
@@ -1,5 +1,7 @@
 # generated by integration tests
-element_2w/**
-element_3w/**
-element_7w/**
-element_8w/**
\ No newline at end of file
+element_4w/**
+element_5w/**
+element_6w/**
+element_10w/**
+element_12w/**
+element_31b/**
\ No newline at end of file

```

File: ecc/bls12-377/fp/element_amd64.go [hunk 1]
```diff
@@ -7,6 +7,12 @@
 
 package fp
 
+import (
```
Comment (ivokub) [inline ecc/bls12-377/fp/element_amd64.go:10]: This works. But couldn't we just do
```
import _ "github.com/consensys/gnark-crypto/field/asm/element_6w"
```
and not import the dummy constant at all?

**Comment by ivokub** [comment]
Suggested edit:
```diff
diff --git a/field/generator/asm/amd64/build.go b/field/generator/asm/amd64/build.go
index 41219d576..a63a1f6cb 100644
--- a/field/generator/asm/amd64/build.go
+++ b/field/generator/asm/amd64/build.go
@@ -284,7 +284,7 @@ func ElementASMFileName(nbWords, nbBits int) string {
 	const fWN = "element_%dw"
 
 	if nbWords == 1 {
-		return filepath.Join(fmt.Sprintf(fW1, 31), fmt.Sprintf(nameW1, 31))
+		return filepath.Join(fmt.Sprintf(fW1, nbBits), fmt.Sprintf(nameW1, nbBits))
 	}
 	return filepath.Join(fmt.Sprintf(fWN, nbWords), fmt.Sprintf(nameWN, nbWords))
 }
@@ -294,7 +294,7 @@ func ElementASMBaseDir(nbWords, nbBits int) string {
 	const fWN = "element_%dw"
 
 	if nbWords == 1 {
-		return fmt.Sprintf(fW1, 31)
+		return fmt.Sprintf(fW1, nbBits)
 	}
 	return fmt.Sprintf(fWN, nbWords)
 }
diff --git a/field/generator/asm/arm64/build.go b/field/generator/asm/arm64/build.go
index d6f035551..1fb96c9f1 100644
--- a/field/generator/asm/arm64/build.go
+++ b/field/generator/asm/arm64/build.go
@@ -220,7 +220,7 @@ func ElementASMFileName(nbWords, nbBits int) string {
 	const fW1 = "element_%db"
 	const fWN = "element_%dw"
 	if nbWords == 1 {
-		return filepath.Join(fmt.Sprintf(fW1, 31), fmt.Sprintf(nameW1, 31))
+		return filepath.Join(fmt.Sprintf(fW1, nbBits), fmt.Sprintf(nameW1, nbBits))
 	}
 	return filepath.Join(fmt.Sprintf(fWN, nbWords), fmt.Sprintf(nameWN, nbWords))
 }

```

**Review by ivokub — APPROVED** [review]
See suggests and a single comment. Otherwise looks perfect.

**Comment by gbotrel** [comment]
> Suggested edit:
> 
> ```diff
> diff --git a/field/asm/.gitignore b/field/asm/.gitignore
> index d21c226a7..d9d3470d3 100644
> --- a/field/asm/.gitignore
> +++ b/field/asm/.gitignore
> @@ -1,5 +1,7 @@
>  # generated by integration tests
> -element_2w/**
> -element_3w/**
> -element_7w/**
> -element_8w/**
> \ No newline at end of file
> +element_4w/**
> +element_5w/**
> +element_6w/**
> +element_10w/**
> +element_12w/**
> +element_31b/**
> \ No newline at end of file
> ```

can't do, we need 4w etc they are imported :-)

File: ecc/bls12-377/fp/element_amd64.go (hunk 1 above)
Comment (gbotrel) [reply ecc/bls12-377/fp/element_amd64.go:10]: probably yes, will try 👍
